apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-agent-config
  namespace: ansible-system
  labels:
    app: ansible-agent
data:
  # Rate limiting configuration
  GLOBAL_RATE_LIMIT: "100 per hour"
  PER_IP_RATE_LIMIT: "1 per 5 minutes"
  
  # Security configuration
  MAX_HOSTNAME_LENGTH: "253"
  MIN_HOSTNAME_LENGTH: "1"
  
  # Application configuration
  PORT: "5000"
  FLASK_ENV: "production"
  
  # Redis configuration (if using Redis for rate limiting)
  REDIS_URL: "redis://redis:6379"